package io.github.clicksilver.exporter;

import java.lang.String;
import java.util.HashMap;

public class WikiDB {
  static final String[] kDecoNames = {
    "Defense Jewel+ 4",
    "Hard Defense Jewel 4",
    "Recovery Jewel+ 4",
    "Fire Res Jewel+ 4",
    "Hard Fire Res Jewel 4",
    "Water Res Jewel+ 4",
    "Hard Water Res Jewel 4",
    "Ice Res Jewel+ 4",
    "Hard Ice Res Jewel 4",
    "Thunder Res Jewel+ 4",
    "Hard Thunder Res Jewel 4",
    "Dragon Res Jewel+ 4",
    "Hard Dragon Res Jewel 4",
    "Antidote Jewel+ 4",
    "Antipara Jewel+ 4",
    "Pep Jewel+ 4",
    "Antiblast Jewel+ 4",
    "Steadfast Jewel+ 4",
    "Suture Jewel+ 4",
    "Def Lock Jewel+ 4",
    "Miasma Jewel+ 4",
    "Wind Resist Jewel+ 4",
    "Expert Jewel+ 4",
    "Blaze Jewel+ 4",
    "Stream Jewel+ 4",
    "Frost Jewel+ 4",
    "Bolt Jewel+ 4",
    "Dragon Jewel+ 4",
    "Venom Jewel+ 4",
    "Paralyzer Jewel+ 4",
    "Sleep Jewel+ 4",
    "Blast Jewel+ 4",
    "Artillery Jewel+ 4",
    "Sonorous Jewel+ 4",
    "Potential Jewel+ 4",
    "Physique Jewel+ 4",
    "Hungerless Jewel+ 4",
    "Enduring Jewel+ 4",
    "Hard Enduring Jewel 4",
    "Friendship Jewel+ 4",
    "Specimen Jewel+ 4",
    "Hard Specimen Jewel 4",
    "Botany Jewel+ 4",
    "Hard Botany Jewel 4",
    "Geology Jewel+ 4",
    "Hard Geology Jewel 4",
    "Survival Jewel+ 4",
    "Hard Survival Jewel 4",
    "Mirewalker Jewel+ 4",
    "Intimidator Jewel+ 4",
    "Hard Intimidator Jewel 4",
    "Tip Toe Jewel+ 4",
    "Hard Tip Toe Jewel 4",
    "Meowster Jewel+ 4",
    "Hard Meowster Jewel 4",
    "Evasion Jewel+ 4",
    "Earplug Jewel+ 4",
    "Ironwall Jewel+ 4",
    "Heavy Artillery Jewel+ 4",
    "Furor Jewel+ 4",
    "Attack Jewel+ 4",
    "Challenger Jewel+ 4",
    "Trueshot Jewel+ 4",
    "Throttle Jewel+ 4",
    "Handicraft Jewel+ 4",
    "Brace/Protection Jewel 4",
    "Wind Resist/Protection Jewel 4",
    "Footing/Protection Jewel 4",
    "Draw/Protection Jewel 4",
    "Enhancer/Protection Jewel 4",
    "Charger/Protection Jewel 4",
    "Destroyer/Protection Jewel 4",
    "KO/Protection Jewel 4",
    "Throttle/Protection Jewel 4",
    "Challenger/Protection Jewel 4",
    "Flawless/Protection Jewel 4",
    "Potential/Protection Jewel 4",
    "Mighty/Protection Jewel 4",
    "Furor/Protection Jewel 4",
    "Phoenix/Protection Jewel 4",
    "Earplug/Protection Jewel 4",
    "Critical/Protection Jewel 4",
    "Tenderizer/Protection Jewel 4",
    "Handicraft/Protection Jewel 4",
    "Release/Protection Jewel 4",
    "Brace/Vitality Jewel 4",
    "Wind Resist/Vitality Jewel 4",
    "Footing/Vitality Jewel 4",
    "Draw/Vitality Jewel 4",
    "Enhancer/Vitality Jewel 4",
    "Charger/Vitality Jewel 4",
    "Destroyer/Vitality Jewel 4",
    "KO/Vitality Jewel 4",
    "Throttle/Vitality Jewel 4",
    "Challenger/Vitality Jewel 4",
    "Flawless/Vitality Jewel 4",
    "Potential/Vitality Jewel 4",
    "Mighty/Vitality Jewel 4",
    "Furor/Vitality Jewel 4",
    "Phoenix/Vitality Jewel 4",
    "Earplug/Vitality Jewel 4",
    "Critical/Vitality Jewel 4",
    "Tenderizer/Vitality Jewel 4",
    "Handicraft/Vitality Jewel 4",
    "Release/Vitality Jewel 4",
    "Brace/Medicine Jewel 4",
    "Wind Resist/Medicine Jewel 4",
    "Footing/Medicine Jewel 4",
    "Draw/Medicine Jewel 4",
    "Enhancer/Medicine Jewel 4",
    "Charger/Medicine Jewel 4",
    "Destroyer/Medicine Jewel 4",
    "KO/Medicine Jewel 4",
    "Throttle/Medicine Jewel 4",
    "Challenger/Medicine Jewel 4",
    "Flawless/Medicine Jewel 4",
    "Potential/Medicine Jewel 4",
    "Mighty/Medicine Jewel 4",
    "Furor/Medicine Jewel 4",
    "Phoenix/Medicine Jewel 4",
    "Earplug/Medicine Jewel 4",
    "Critical/Medicine Jewel 4",
    "Tenderizer/Medicine Jewel 4",
    "Handicraft/Medicine Jewel 4",
    "Release/Medicine Jewel 4",
    "Resistor/Attack Jewel 4",
    "Drain/Attack Jewel 4",
    "Flight/Attack Jewel 4",
    "Sheath/Attack Jewel 4",
    "Fortitude/Attack Jewel 4",
    "Slider/Attack Jewel 4",
    "Sprinter/Attack Jewel 4",
    "Refresh/Attack Jewel 4",
    "Crisis/Attack Jewel 4",
    "Jumping/Attack Jewel 4",
    "Ironwall/Attack Jewel 4",
    "Guardian/Attack Jewel 4",
    "Friendship/Attack Jewel 4",
    "Gobbler/Attack Jewel 4",
    "Satiated/Attack Jewel 4",
    "Grinder/Attack Jewel 4",
    "Bomber/Attack Jewel 4",
    "Fungiform/Attack Jewel 4",
    "Stonethrower/Attack Jewel 4",
    "Resistor/Expert Jewel 4",
    "Drain/Expert Jewel 4",
    "Flight/Expert Jewel 4",
    "Sheath/Expert Jewel 4",
    "Fortitude/Expert Jewel 4",
    "Slider/Expert Jewel 4",
    "Sprinter/Expert Jewel 4",
    "Refresh/Expert Jewel 4",
    "Crisis/Expert Jewel 4",
    "Jumping/Expert Jewel 4",
    "Ironwall/Expert Jewel 4",
    "Guardian/Expert Jewel 4",
    "Friendship/Expert Jewel 4",
    "Gobbler/Expert Jewel 4",
    "Satiated/Expert Jewel 4",
    "Grinder/Expert Jewel 4",
    "Bomber/Expert Jewel 4",
    "Fungiform/Expert Jewel 4",
    "Stonethrower/Expert Jewel 4",
    "Resistor/Handicraft Jewel 4",
    "Drain/Handicraft Jewel 4",
    "Flight/Handicraft Jewel 4",
    "Sheath/Handicraft Jewel 4",
    "Fortitude/Handicraft Jewel 4",
    "Slider/Handicraft Jewel 4",
    "Sprinter/Handicraft Jewel 4",
    "Refresh/Handicraft Jewel 4",
    "Crisis/Handicraft Jewel 4",
    "Jumping/Handicraft Jewel 4",
    "Ironwall/Handicraft Jewel 4",
    "Guardian/Handicraft Jewel 4",
    "Friendship/Handicraft Jewel 4",
    "Gobbler/Handicraft Jewel 4",
    "Satiated/Handicraft Jewel 4",
    "Grinder/Handicraft Jewel 4",
    "Bomber/Handicraft Jewel 4",
    "Fungiform/Handicraft Jewel 4",
    "Stonethrower/Handicraft Jewel 4",
    "Resistor/Release Jewel 4",
    "Drain/Release Jewel 4",
    "Flight/Release Jewel 4",
    "Sheath/Release Jewel 4",
    "Fortitude/Release Jewel 4",
    "Slider/Release Jewel 4",
    "Sprinter/Release Jewel 4",
    "Refresh/Release Jewel 4",
    "Crisis/Release Jewel 4",
    "Jumping/Release Jewel 4",
    "Ironwall/Release Jewel 4",
    "Guardian/Release Jewel 4",
    "Friendship/Release Jewel 4",
    "Gobbler/Release Jewel 4",
    "Satiated/Release Jewel 4",
    "Grinder/Release Jewel 4",
    "Bomber/Release Jewel 4",
    "Fungiform/Release Jewel 4",
    "Stonethrower/Release Jewel 4",
    "Brace/Physique Jewel 4",
    "Wind Resist/Physique Jewel 4",
    "Footing/Physique Jewel 4",
    "Draw/Physique Jewel 4",
    "Enhancer/Physique Jewel 4",
    "Charger/Physique Jewel 4",
    "Destroyer/Physique Jewel 4",
    "KO/Physique Jewel 4",
    "Throttle/Physique Jewel 4",
    "Challenger/Physique Jewel 4",
    "Flawless/Physique Jewel 4",
    "Potential/Physique Jewel 4",
    "Mighty/Physique Jewel 4",
    "Furor/Physique Jewel 4",
    "Phoenix/Physique Jewel 4",
    "Earplug/Physique Jewel 4",
    "Critical/Physique Jewel 4",
    "Tenderizer/Physique Jewel 4",
    "Handicraft/Physique Jewel 4",
    "Release/Physique Jewel 4",
    "Resistor/Physique Jewel 4",
    "Drain/Physique Jewel 4",
    "Flight/Physique Jewel 4",
    "Sheath/Physique Jewel 4",
    "Fortitude/Physique Jewel 4",
    "Slider/Physique Jewel 4",
    "Sprinter/Physique Jewel 4",
    "Refresh/Physique Jewel 4",
    "Crisis/Physique Jewel 4",
    "Jumping/Physique Jewel 4",
    "Ironwall/Physique Jewel 4",
    "Guardian/Physique Jewel 4",
    "Friendship/Physique Jewel 4",
    "Gobbler/Physique Jewel 4",
    "Satiated/Physique Jewel 4",
    "Grinder/Physique Jewel 4",
    "Bomber/Physique Jewel 4",
    "Fungiform/Physique Jewel 4",
    "Stonethrower/Physique Jewel 4",
    "Brace/Evasion Jewel 4",
    "Wind Resist/Evasion Jewel 4",
    "Footing/Evasion Jewel 4",
    "Draw/Evasion Jewel 4",
    "Enhancer/Evasion Jewel 4",
    "Charger/Evasion Jewel 4",
    "Destroyer/Evasion Jewel 4",
    "KO/Evasion Jewel 4",
    "Throttle/Evasion Jewel 4",
    "Challenger/Evasion Jewel 4",
    "Flawless/Evasion Jewel 4",
    "Potential/Evasion Jewel 4",
    "Mighty/Evasion Jewel 4",
    "Furor/Evasion Jewel 4",
    "Phoenix/Evasion Jewel 4",
    "Earplug/Evasion Jewel 4",
    "Critical/Evasion Jewel 4",
    "Tenderizer/Evasion Jewel 4",
    "Handicraft/Evasion Jewel 4",
    "Release/Evasion Jewel 4",
    "Resistor/Evasion Jewel 4",
    "Drain/Evasion Jewel 4",
    "Flight/Evasion Jewel 4",
    "Sheath/Evasion Jewel 4",
    "Fortitude/Evasion Jewel 4",
    "Slider/Evasion Jewel 4",
    "Sprinter/Evasion Jewel 4",
    "Refresh/Evasion Jewel 4",
    "Crisis/Evasion Jewel 4",
    "Jumping/Evasion Jewel 4",
    "Ironwall/Evasion Jewel 4",
    "Guardian/Evasion Jewel 4",
    "Friendship/Evasion Jewel 4",
    "Gobbler/Evasion Jewel 4",
    "Satiated/Evasion Jewel 4",
    "Grinder/Evasion Jewel 4",
    "Bomber/Evasion Jewel 4",
    "Fungiform/Evasion Jewel 4",
    "Stonethrower/Evasion Jewel 4",
    "Brace/Maintenance Jewel 4",
    "Wind Resist/Maintenance Jewel 4",
    "Footing/Maintenance Jewel 4",
    "Draw/Maintenance Jewel 4",
    "Enhancer/Maintenance Jewel 4",
    "Charger/Maintenance Jewel 4",
    "Destroyer/Maintenance Jewel 4",
    "KO/Maintenance Jewel 4",
    "Throttle/Maintenance Jewel 4",
    "Challenger/Maintenance Jewel 4",
    "Flawless/Maintenance Jewel 4",
    "Potential/Maintenance Jewel 4",
    "Mighty/Maintenance Jewel 4",
    "Furor/Maintenance Jewel 4",
    "Phoenix/Maintenance Jewel 4",
    "Earplug/Maintenance Jewel 4",
    "Critical/Maintenance Jewel 4",
    "Tenderizer/Maintenance Jewel 4",
    "Handicraft/Maintenance Jewel 4",
    "Release/Maintenance Jewel 4",
  };

  static final String[] kDecoJapaneseNames = {
    "防御珠Ⅱ【４】",
    "防御珠Ⅲ【４】",
    "早復珠Ⅱ【４】",
    "耐火珠Ⅱ【４】",
    "耐火珠Ⅲ【４】",
    "耐水珠Ⅱ【４】",
    "耐水珠Ⅲ【４】",
    "耐氷珠Ⅱ【４】",
    "耐氷珠Ⅲ【４】",
    "耐雷珠Ⅱ【４】",
    "耐雷珠Ⅲ【４】",
    "耐龍珠Ⅱ【４】",
    "耐龍珠Ⅲ【４】",
    "耐毒珠Ⅱ【４】",
    "耐麻珠Ⅱ【４】",
    "耐眠珠Ⅱ【４】",
    "耐爆珠Ⅱ【４】",
    "耐絶珠Ⅱ【４】",
    "耐裂珠Ⅱ【４】",
    "耐防珠Ⅱ【４】",
    "耐瘴珠Ⅱ【４】",
    "防風珠Ⅱ【４】",
    "達人珠Ⅱ【４】",
    "火炎珠Ⅱ【４】",
    "流水珠Ⅱ【４】",
    "氷結珠Ⅱ【４】",
    "雷光珠Ⅱ【４】",
    "破龍珠Ⅱ【４】",
    "毒珠Ⅱ【４】",
    "麻痺珠Ⅱ【４】",
    "睡眠珠Ⅱ【４】",
    "爆破珠Ⅱ【４】",
    "砲術珠Ⅱ【４】",
    "鼓笛珠Ⅱ【４】",
    "底力珠Ⅱ【４】",
    "体術珠Ⅱ【４】",
    "無食珠Ⅱ【４】",
    "持続珠Ⅱ【４】",
    "持続珠Ⅲ【４】",
    "友愛珠Ⅱ【４】",
    "標本珠Ⅱ【４】",
    "標本珠Ⅲ【４】",
    "植学珠Ⅱ【４】",
    "植学珠Ⅳ【４】",
    "砲手珠Ⅱ【４】",
    "地学珠Ⅱ【４】",
    "地学珠Ⅲ【４】",
    "環境珠Ⅱ【４】",
    "環境珠Ⅲ【４】",
    "沼渡珠Ⅱ【４】",
    "威嚇珠Ⅱ【４】",
    "威嚇珠Ⅲ【４】",
    "潜伏珠Ⅱ【４】",
    "潜伏珠Ⅲ【４】",
    "采配珠Ⅱ【４】",
    "采配珠Ⅲ【４】",
    "回避珠Ⅱ【４】",
    "防音珠Ⅱ【４】",
    "鉄壁珠Ⅱ【４】",
    "逆上珠Ⅱ【４】",
    "攻撃珠Ⅱ【４】",
    "挑戦珠Ⅱ【４】",
    "特射珠Ⅱ【４】",
    "全開珠Ⅱ【４】",
    "匠珠Ⅱ【４】",
    "防風・加護珠【４】",
    "耐震・加護珠【４】",
    "耐衝・加護珠【４】",
    "抜刀・加護珠【４】",
    "短縮・加護珠【４】",
    "昂揚・加護珠【４】",
    "重撃・加護珠【４】",
    "ＫＯ・加護珠【４】",
    "全開・加護珠【４】",
    "挑戦・加護珠【４】",
    "無傷・加護珠【４】",
    "底力・加護珠【４】",
    "逆上・加護珠【４】",
    "渾身・加護珠【４】",
    "転福・加護珠【４】",
    "防音・加護珠【４】",
    "超心・加護珠【４】",
    "痛撃・加護珠【４】",
    "匠・加護珠【４】",
    "解放・加護珠【４】",
    "防風・体力珠【４】",
    "耐震・体力珠【４】",
    "耐衝・体力珠【４】",
    "抜刀・体力珠【４】",
    "短縮・体力珠【４】",
    "昂揚・体力珠【４】",
    "重撃・体力珠【４】",
    "ＫＯ・体力珠【４】",
    "全開・体力珠【４】",
    "挑戦・体力珠【４】",
    "無傷・体力珠【４】",
    "底力・体力珠【４】",
    "逆上・体力珠【４】",
    "渾身・体力珠【４】",
    "転福・体力珠【４】",
    "防音・体力珠【４】",
    "超心・体力珠【４】",
    "痛撃・体力珠【４】",
    "匠・体力珠【４】",
    "解放・体力珠【４】",
    "防風・治癒珠【４】",
    "耐震・治癒珠【４】",
    "耐衝・治癒珠【４】",
    "抜刀・治癒珠【４】",
    "短縮・治癒珠【４】",
    "昂揚・治癒珠【４】",
    "重撃・治癒珠【４】",
    "ＫＯ・治癒珠【４】",
    "全開・治癒珠【４】",
    "挑戦・治癒珠【４】",
    "無傷・治癒珠【４】",
    "底力・治癒珠【４】",
    "逆上・治癒珠【４】",
    "渾身・治癒珠【４】",
    "転福・治癒珠【４】",
    "防音・治癒珠【４】",
    "超心・治癒珠【４】",
    "痛撃・治癒珠【４】",
    "匠・治癒珠【４】",
    "解放・治癒珠【４】",
    "耐属・攻撃珠【４】",
    "奪気・攻撃珠【４】",
    "飛燕・攻撃珠【４】",
    "速納・攻撃珠【４】",
    "逆境・攻撃珠【４】",
    "滑走・攻撃珠【４】",
    "強走・攻撃珠【４】",
    "早気・攻撃珠【４】",
    "窮地・攻撃珠【４】",
    "跳躍・攻撃珠【４】",
    "鉄壁・攻撃珠【４】",
    "守勢・攻撃珠【４】",
    "友愛・攻撃珠【４】",
    "早食・攻撃珠【４】",
    "節食・攻撃珠【４】",
    "研磨・攻撃珠【４】",
    "爆師・攻撃珠【４】",
    "茸好・攻撃珠【４】",
    "投石・攻撃珠【４】",
    "耐属・達人珠【４】",
    "奪気・達人珠【４】",
    "飛燕・達人珠【４】",
    "速納・達人珠【４】",
    "逆境・達人珠【４】",
    "滑走・達人珠【４】",
    "強走・達人珠【４】",
    "早気・達人珠【４】",
    "窮地・達人珠【４】",
    "跳躍・達人珠【４】",
    "鉄壁・達人珠【４】",
    "守勢・達人珠【４】",
    "友愛・達人珠【４】",
    "早食・達人珠【４】",
    "節食・達人珠【４】",
    "研磨・達人珠【４】",
    "爆師・達人珠【４】",
    "茸好・達人珠【４】",
    "投石・達人珠【４】",
    "耐属・匠珠【４】",
    "奪気・匠珠【４】",
    "飛燕・匠珠【４】",
    "速納・匠珠【４】",
    "逆境・匠珠【４】",
    "滑走・匠珠【４】",
    "強走・匠珠【４】",
    "早気・匠珠【４】",
    "窮地・匠珠【４】",
    "跳躍・匠珠【４】",
    "鉄壁・匠珠【４】",
    "守勢・匠珠【４】",
    "友愛・匠珠【４】",
    "早食・匠珠【４】",
    "節食・匠珠【４】",
    "研磨・匠珠【４】",
    "爆師・匠珠【４】",
    "茸好・匠珠【４】",
    "投石・匠珠【４】",
    "耐属・解放珠【４】",
    "奪気・解放珠【４】",
    "飛燕・解放珠【４】",
    "速納・解放珠【４】",
    "逆境・解放珠【４】",
    "滑走・解放珠【４】",
    "強走・解放珠【４】",
    "早気・解放珠【４】",
    "窮地・解放珠【４】",
    "跳躍・解放珠【４】",
    "鉄壁・解放珠【４】",
    "守勢・解放珠【４】",
    "友愛・解放珠【４】",
    "早食・解放珠【４】",
    "節食・解放珠【４】",
    "研磨・解放珠【４】",
    "爆師・解放珠【４】",
    "茸好・解放珠【４】",
    "投石・解放珠【４】",
    "防風・体術珠【４】",
    "耐震・体術珠【４】",
    "耐衝・体術珠【４】",
    "抜刀・体術珠【４】",
    "短縮・体術珠【４】",
    "昂揚・体術珠【４】",
    "重撃・体術珠【４】",
    "ＫＯ・体術珠【４】",
    "全開・体術珠【４】",
    "挑戦・体術珠【４】",
    "無傷・体術珠【４】",
    "底力・体術珠【４】",
    "逆上・体術珠【４】",
    "渾身・体術珠【４】",
    "転福・体術珠【４】",
    "防音・体術珠【４】",
    "超心・体術珠【４】",
    "痛撃・体術珠【４】",
    "匠・体術珠【４】",
    "解放・体術珠【４】",
    "耐属・体術珠【４】",
    "奪気・体術珠【４】",
    "飛燕・体術珠【４】",
    "速納・体術珠【４】",
    "逆境・体術珠【４】",
    "滑走・体術珠【４】",
    "強走・体術珠【４】",
    "早気・体術珠【４】",
    "窮地・体術珠【４】",
    "跳躍・体術珠【４】",
    "鉄壁・体術珠【４】",
    "守勢・体術珠【４】",
    "友愛・体術珠【４】",
    "早食・体術珠【４】",
    "節食・体術珠【４】",
    "研磨・体術珠【４】",
    "爆師・体術珠【４】",
    "茸好・体術珠【４】",
    "投石・体術珠【４】",
    "防風・回避珠【４】",
    "耐震・回避珠【４】",
    "耐衝・回避珠【４】",
    "抜刀・回避珠【４】",
    "短縮・回避珠【４】",
    "昂揚・回避珠【４】",
    "重撃・回避珠【４】",
    "ＫＯ・回避珠【４】",
    "全開・回避珠【４】",
    "挑戦・回避珠【４】",
    "無傷・回避珠【４】",
    "底力・回避珠【４】",
    "逆上・回避珠【４】",
    "渾身・回避珠【４】",
    "転福・回避珠【４】",
    "防音・回避珠【４】",
    "超心・回避珠【４】",
    "痛撃・回避珠【４】",
    "匠・回避珠【４】",
    "解放・回避珠【４】",
    "耐属・回避珠【４】",
    "奪気・回避珠【４】",
    "飛燕・回避珠【４】",
    "速納・回避珠【４】",
    "逆境・回避珠【４】",
    "滑走・回避珠【４】",
    "強走・回避珠【４】",
    "早気・回避珠【４】",
    "窮地・回避珠【４】",
    "跳躍・回避珠【４】",
    "鉄壁・回避珠【４】",
    "守勢・回避珠【４】",
    "友愛・回避珠【４】",
    "早食・回避珠【４】",
    "節食・回避珠【４】",
    "研磨・回避珠【４】",
    "爆師・回避珠【４】",
    "茸好・回避珠【４】",
    "投石・回避珠【４】",
    "防風・整備珠【４】",
    "耐震・整備珠【４】",
    "耐衝・整備珠【４】",
    "抜刀・整備珠【４】",
    "短縮・整備珠【４】",
    "昂揚・整備珠【４】",
    "重撃・整備珠【４】",
    "ＫＯ・整備珠【４】",
    "全開・整備珠【４】",
    "挑戦・整備珠【４】",
    "無傷・整備珠【４】",
    "底力・整備珠【４】",
    "逆上・整備珠【４】",
    "渾身・整備珠【４】",
    "転福・整備珠【４】",
    "防音・整備珠【４】",
    "超心・整備珠【４】",
    "痛撃・整備珠【４】",
    "匠・整備珠【４】",
    "解放・整備珠【４】",
  };

  static final int kNumDecos = kDecoNames.length;

  // Used to format the output string for exporting to Honey Hunter.
  static HashMap<String, Integer> kNameToOrdering;

  // Whether the above HashMaps are preloaded for quick queries.
  static boolean loaded = false;

  public static void LoadTables() {
    if (loaded) {
      return;
    }
    kNameToOrdering = new HashMap<String, Integer>();
    for(int i=0; i<kDecoNames.length; i++) {
      kNameToOrdering.put(kDecoNames[i], i);
    }
    loaded = true;
  }

  public static int getOrderingFromName(String name) {
    LoadTables();
    if (!kNameToOrdering.containsKey(name)) {
      return -1;
    }
    return kNameToOrdering.get(name);
  }
}
